import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <html>
          <title>Form Builder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </html>
      </Head>
      <div className="w-full h-screen bg-primary-black">
        <Component {...pageProps} />
      </div>
    </>
  );
}
